### ISSUE TITLE
Modernise package

### ISSUE THREAD

**Issue by freekmurze** [spatie/menu#119]
- Drop StyleCI
- Drop Travis
- Use GitHub workflows
- Update badges in readme
- Drop anything below PHP 7.4
- Use PHP 7.4 where possible
- Make sure testsuite runs
- Tag new version

**Comment by sebastiandedeyne** [comment]
Since this package has a lot of users (us included) I don't think we should drop it. Having said that, I'd invest in modernizing it to work with PHP 8, but would rather put more effort into our new laravel-navigation package.

**Comment by rubenvanassche** [comment]
So I've just released 2.9.0, this includes the following:

- Drop support for anything bellow PHP 7.1
- Added support for PH¨8.0, because why not?
- Dropped StyleCI, Travis
- Fixed the test suite
- Added Github actions for tests and updated the badges
- Also added Psalm and updated the codebase so it's correct
- And added our styling action
- Also added some files in the /.github dir with information about contributing, funding and security
